import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

export default function About() {
    return (
        <>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='bg-white px-10'>
                <section className="min-h-screen">
                <nav className='py-10 mb-12 flex justify-between'>
                    <h1 className='text-xl font-burtons'><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='/'>Home</a></h1>
                    <ul className='flex items-center'>
                    <li>
                        <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
                    </li>
                    <li>
                        <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
                    </li>
                    </ul>
                </nav>

                <div className='text-center p-10'>
                    <h2 className='text-5xl py-2 text-teal-600 font-medium'>Kenneth Lek Qi Yu</h2>
                    <h3 className='text-2xl py-2'>Technical Product Consultant</h3>
                    <h4 className='text-xl py-2'>Moody's Analytics</h4>
                    <p className='text-md py-5 leading-8 text-gray-800'>Hi I like to code</p>
                </div>
                
                
                </section>
            </main>
        </>
    )
}